### PR TITLE
Generate random harps for Angels and Aleax

### PR DESCRIPTION
**Pull request by RojjaCebolla**
If xnh later adds additional humanoid angelic beings who are not "lords", then those would qualify to have harps as well.

### CODE REVIEW

**Comment by copperwater** [comment]
This is actually planned for 7.0! However, 80% of the harps being magic is way too much. Maybe 10% instead.

**Comment by RojjaCebolla** [comment]
whoops, meant for it to be 20%, not 80%. (it'd be a nice round number: 1 in 100 angels/aleaxes have a magic harp and 1 in 25 have a wooden one; no archons kirin or couatl do)

**Comment by copperwater** [comment]
So I crunched the numbers on it. On Astral, there are 24 Angels generated, plus 6 random A (let's say 3 of them become Angels or Aleaxes) plus 3+2d3 Angels for each wing that opens up into a large room, expected value 7 per wing. The wings have a 60% generation probability, so on average you expect to see about 8 additional Angels, though it could be as low as 0 in the 16% chance that neither wing opens or as high as 18 when both wings open. The grand total of Angels is thus around 25-45.

35 Angels/Aleaxes with a 1% chance of a magic harp apiece has a 29.65% chance that at least one magic harp generates, a 4.78% chance of at least two. The chances drop to 16.09% and 1.33% if the chance of the harp being magic is reduced to 10% per angel.

On the other hand, the player doesn't typically kill and loot every Angel on Astral, and the value of a magic harp that late in the game is questionable. So I think I'm fine with the 20% chance. Please fix it to 20% and I'll merge it.

**Comment by RojjaCebolla** [comment]
hm, i thought there was a way to squash commits here on Github, but the only option seems to be local squashing, followed by force lightning

**Comment by copperwater** [comment]
Cherry-picked into 6.0-compat branch.

**Pull request closed without merging**
